spring:
  datasource:
    url: jdbc:mysql://mysql:3306/luckysix?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: chenfei123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#      记录一次大坑！！！，redis应该交由spring管理.项目上线报错.
  redis:
    host: redis
    port: 6379
    timeout: 1000
    jedis:
      pool:
        min-idle: 5
        max-idle: 10
        max-wait: -1

server:
  port: 80



#mp日志  //生产环境不需要打印sql日志
mybatis-plus:
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    开启驼峰自动转化
    map-underscore-to-camel-case: true

files:
  upload:
    path: /opt/myblog/uploadFile/






















