version: "3"

services:
  microService:
    image: myblog:1.0.0
    container_name: myblog
    ports:
      - "80:80"
    volumes:
      - /app/microService:/data
    networks:
      - lucky_six
    depends_on:
      - redis
      - mysql

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /app/redis/redis.conf:/etc/redis/redis.conf
      - /app/redis/data:/data
    networks:
      - lucky_six
    command: redis-server /etc/redis/redis.conf

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - /app/mysql/db:/var/lib/mysql
      - /app/mysql/conf/my.cnf:/etc/my.cnf
      - /app/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - lucky_six
    command: --default-authentication-plugin=mysql_native_password #解决外部无法访问

networks:
  lucky_six:
